a=input('enter first number:')
b=input('enter second number:')
sum=float(a)+float(b)
min=float(a)-float(b)
mul=float(a)*float(b)
div=float(a)/float(b)
print("the sum of{0} and{1}is{2}".format(a,b,sum))
print("the substraction of {0}and{1}is{2}".format(a,b,min))
print("the multiplication of {0}and{1}is{2}".format(a,b,mul))
print("the division of {0}and{1}is{2}".format(a,b,div))